server:
  port: 8081
spring: 
  data: 
    mongodb:
      host: localhost
      port: 27017
      database: kafkamongodb
  kafka: 
    consumer:
      bootstrap-servers: localhost:9092
      group-id: "id"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer: 
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
